### ISSUE TITLE
Not compatible with td-agent 0.12.29

### ISSUE THREAD

**Issue by serialoverflow** [fluent/fluent-plugin-grok-parser#22]
Hi,

when trying to use this plugin with td-agent 0.12.29 on centOS i get the following error:

```
2016-10-20 16:14:12 +0200 [info]: adding match pattern="td.*.*" type="tdlog"  
/opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2112:in `raise_if_conflicts': Unable to activate td-client-0.8.83, because msgpack-1.0.2 conflicts with msgpack (!= 0.5.0, != 0.5.1, != 0.5.2, != 0.5.3, < 0.8.0, >= 0.4.4) (Gem::ConflictError)    
        from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1280:in `activate'                              
        from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:198:in `rescue in try_activate'                               
        from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:195:in `try_activate'                                         
        from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'            
        from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:39:in `require'                       
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-td-0.10.29/lib/fluent/plugin/out_tdlog.rb:1:in `<top (required)>'                                                                                                                                  
        from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'                       
        from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'                       
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.8/lib/fluent/registry.rb:94:in `block in search'             
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.8/lib/fluent/registry.rb:92:in `each'                        
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.8/lib/fluent/registry.rb:92:in `search'                      
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.8/lib/fluent/registry.rb:43:in `lookup'                      
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.8/lib/fluent/plugin.rb:146:in `new_impl'                     
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.8/lib/fluent/plugin.rb:104:in `new_output'                   
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.8/lib/fluent/agent.rb:125:in `add_match'                     
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.8/lib/fluent/agent.rb:70:in `block in configure'             
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.8/lib/fluent/agent.rb:63:in `each'                           
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.8/lib/fluent/agent.rb:63:in `configure'                      
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.8/lib/fluent/root_agent.rb:86:in `configure'                 
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.8/lib/fluent/engine.rb:119:in `configure'                    
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.8/lib/fluent/engine.rb:93:in `run_configure'                 
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.8/lib/fluent/supervisor.rb:693:in `run_configure'            
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.8/lib/fluent/supervisor.rb:453:in `block in run_worker'      
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.8/lib/fluent/supervisor.rb:626:in `call'                     
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.8/lib/fluent/supervisor.rb:626:in `main_process'             
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.8/lib/fluent/supervisor.rb:449:in `run_worker'               
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.8/lib/fluent/command/fluentd.rb:288:in `<top (required)>'    
        from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'                       
        from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'                       
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.8/bin/fluentd:5:in `<top (required)>'                        
        from /opt/td-agent/embedded/bin/fluentd:23:in `load'                                                                           
        from /opt/td-agent/embedded/bin/fluentd:23:in `<top (required)>'                                                               
        from /sbin/td-agent:7:in `load'                                                                                                
        from /sbin/td-agent:7:in `<main>' 
2016-10-20 16:14:12 +0200 [info]: Worker 0 finished unexpectedly with status 1 
```

**Comment by okkez** [comment]
You can use this plugin version 1.0.0 with Fluetnd v0.12.x

See https://github.com/kiyoto/fluent-plugin-grok-parser#notice
