### ISSUE TITLE
fluentd can not init grok-parser plugin, return error="uninitialized constant Fluent::Plugin::GrokParser::NoneParser"

### ISSUE THREAD

**Issue by yangzb09** [fluent/fluent-plugin-grok-parser#26]
here are output lines:
```
2017-02-06 08:45:38 +0000 [info]: adding filter pattern="apache_access" type="parser"
2017-02-06 08:45:38 +0000 [error]: #0 unexpected error error_class=NameError error="uninitialized constant Fluent::Plugin::GrokParser::NoneParser"
  2017-02-06 08:45:38 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-grok-parser-2.1.0/lib/fluent/plugin/parser_grok.rb:19:in `initialize'
  2017-02-06 08:45:38 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.12/lib/fluent/plugin.rb:149:in `new'
  2017-02-06 08:45:38 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.12/lib/fluent/plugin.rb:149:in `new_impl'
  2017-02-06 08:45:38 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.12/lib/fluent/plugin.rb:123:in `new_parser'
  2017-02-06 08:45:38 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.12/lib/fluent/plugin_helper/parser.rb:89:in `block in configure'
  2017-02-06 08:45:38 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.12/lib/fluent/plugin_helper/parser.rb:85:in `each'
  2017-02-06 08:45:38 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.12/lib/fluent/plugin_helper/parser.rb:85:in `configure'
  2017-02-06 08:45:38 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.12/lib/fluent/plugin/filter_parser.rb:41:in `configure'
  2017-02-06 08:45:38 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.12/lib/fluent/plugin.rb:164:in `configure'
  2017-02-06 08:45:38 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.12/lib/fluent/agent.rb:149:in `add_filter'
  2017-02-06 08:45:38 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.12/lib/fluent/agent.rb:69:in `block in configure'
  2017-02-06 08:45:38 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.12/lib/fluent/agent.rb:64:in `each'
  2017-02-06 08:45:38 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.12/lib/fluent/agent.rb:64:in `configure'
  2017-02-06 08:45:38 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.12/lib/fluent/root_agent.rb:86:in `configure'
  2017-02-06 08:45:38 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.12/lib/fluent/engine.rb:117:in `configure'
  2017-02-06 08:45:38 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.12/lib/fluent/engine.rb:91:in `run_configure'
  2017-02-06 08:45:38 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.12/lib/fluent/supervisor.rb:743:in `run_configure'
  2017-02-06 08:45:38 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.12/lib/fluent/supervisor.rb:494:in `block in run_worker'
  2017-02-06 08:45:38 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.12/lib/fluent/supervisor.rb:671:in `call'
  2017-02-06 08:45:38 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.12/lib/fluent/supervisor.rb:671:in `main_process'
  2017-02-06 08:45:38 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.12/lib/fluent/supervisor.rb:490:in `run_worker'
  2017-02-06 08:45:38 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.12/lib/fluent/command/fluentd.rb:300:in `<top (required)>'
  2017-02-06 08:45:38 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  2017-02-06 08:45:38 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  2017-02-06 08:45:38 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.12/bin/fluentd:5:in `<top (required)>'
  2017-02-06 08:45:38 +0000 [error]: #0 /opt/td-agent/embedded/bin/fluentd:23:in `load'
  2017-02-06 08:45:38 +0000 [error]: #0 /opt/td-agent/embedded/bin/fluentd:23:in `<top (required)>'
  2017-02-06 08:45:38 +0000 [error]: #0 /usr/sbin/td-agent:7:in `load'
  2017-02-06 08:45:38 +0000 [error]: #0 /usr/sbin/td-agent:7:in `<main>'
2017-02-06 08:45:38 +0000 [info]: Worker 0 finished unexpectedly with status 1
```

Here are my setting:
```
<filter apache_access>
  @type parser
  reserve_data true
  key_name message
  <parse>
  @type grok
   grok_pattern \[%{HTTPDATE:Timestamp}\] "(?:%{WORD:http_method} %{NOTSPACE:http_url}(?: HTTP/%{NUMBER:http_version})?|%{DATA:rawrequest})" %{NUMBER:http_status} (?:\d+|-)
   time_key Timestamp
   time_format %d/%b/%Y:%H:%M:%S %z
   keep_time_key true
  </parse>
</filter>
```
after we comment it ,fluentd is well.
Thanks all for help.

**Comment by okkez** [comment]
I've released new version v2.1.1.
Please use it.
