### ISSUE TITLE
multiple multiline pattern w/ and w/o multiline_start_regexp

### ISSUE THREAD

**Issue by nullkarma** [fluent/fluent-plugin-grok-parser#34]
> You can use multiple grok patterns to parse your data.

```<source>
  @type tail
  path /path/to/log
  format multiline_grok
  <grok>
    pattern Started %{WORD:verb} "%{URIPATH:pathinfo}" for %{IP:ip} at %{TIMESTAMP_ISO8601:timestamp}\nProcessing by %{WORD:controller}#%{WORD:action} as %{WORD:format}%{DATA:message}Completed %{NUMBER:response} %{WORD} in %{NUMBER:elapsed} (%{DATA:elapsed_details})
  </grok>
  tag grokked_log
</source>
```

> You can use this parser without `multiline_start_regexp` when you know your data structure perfectly.

Actually, you can't use this pattern with `multiline_start_regexp`.

```
parameter 'multiline_start_regexp' in <grok> ... </grok> is not used
```

How do I handle combined (multi and single line) java logs? Single lines might be generated by a custom log4j pattern.

**Comment by okkez** [comment]
First, could you show me concrete log examples?

You can use `multiline_start_regexp` only once. 

```aconf
<source>
  @type tail
  path /path/to/log
  format multiline_grok
  multiline_start_regexp /^pattern/
  <grok>
    pattern Started %{WORD:verb} "%{URIPATH:pathinfo}" for %{IP:ip} at %{TIMESTAMP_ISO8601:timestamp}\nProcessing by %{WORD:controller}#%{WORD:action} as %{WORD:format}%{DATA:message}Completed %{NUMBER:response} %{WORD} in %{NUMBER:elapsed} (%{DATA:elapsed_details})
  </grok>
  tag grokked_log
</source>
```

**Comment by nullkarma** [comment]
Thanks for your quick response.
Here's an example:

```
2017-07-10T08:17:41.611+0000 | INFO | itemcatalogue | u-4235 | 71253 | com.app.service.itemcatalogue.ItemDataLoader | thread-pool1 | Creating new Item with ID: 5b61d760-c252-49ed-8a30-86ea01b55b0b
2016-07-11T01:24:45.724+0200 | WARN | itemcatalogue | u-984237 | 43856 | com.app.commons.media.providers.RuntimeExceptionMapper | http-listener-2(8) | Unexpected exception occurred in Media API
javax.ejb.TransactionRolledbackLocalException: Exception thrown from bean
	at com.sun.ejb.containers.EJBContainerTransactionManager.checkExceptionClientTx(EJBContainerTransactionManager.java:664)
	at com.sun.ejb.containers.EJBContainerTransactionManager.postInvokeTx(EJBContainerTransactionManager.java:509)
	at com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4569)
	at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2075)
	at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2045)
	...
```

**Comment by okkez** [comment]
https://github.com/fluent-plugins-nursery/fluent-plugin-concat can be helpful for such case.

configuration example:

```aconf
<source>
  @type tail
  path java.log
  format none
  read_from_head true
  tag dummy
  @label @CONCAT
</source>

<label @CONCAT>
  <filter>
    @type concat
    key message
    multiline_start_regexp /RuntimeExceptionMapper/
    multiline_end_regexp /^\s+\.\.\.$/
  </filter>
  <filter>
    @type parser
    key_name message
    <parse>
      @type multiline_grok
      grok_pattern %{GREEDYDATA:mydata}
    </parse>
  </filter>
  <match>
    @type stdout
  </match>
</label>
```

This configuration generates following result:

```
2017-08-17 16:07:04.494383437 +0900 dummy: {"mydata":"2017-07-10T08:17:41.611+0000 | INFO | itemcatalogue | u-4235 | 71253 | com.app.service.itemcatalogue.ItemDataLoader | thread-pool1 | Creating new Item with ID: 5b61d760-c252-49ed-8a30-86ea01b55b0b"}
2017-08-17 16:07:04.494412630 +0900 dummy: {"mydata":"2016-07-11T01:24:45.724+0200 | WARN | itemcatalogue | u-984237 | 43856 | com.app.commons.media.providers.RuntimeExceptionMapper | http-listener-2(8) | Unexpected exception occurred in Media API\njavax.ejb.TransactionRolledbackLocalException: Exception thrown from bean\n\tat com.sun.ejb.containers.EJBContainerTransactionManager.checkExceptionClientTx(EJBContainerTransactionManager.java:664)\n\tat com.sun.ejb.containers.EJBContainerTransactionManager.postInvokeTx(EJBContainerTransactionManager.java:509)\n\tat com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4569)\n\tat com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2075)\n\tat com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2045)\n\t..."}
2017-08-17 16:07:04.494421453 +0900 dummy: {"mydata":"2017-07-10T08:17:41.611+0000 | INFO | itemcatalogue | u-768 | 658678 | com.app.service.itemcatalogue.ItemDataLoader | thread-pool10 | Creating new Item with ID: 5b61d760-c252-49ed-8a30-86ea01b55b0b"}
```

**Comment by nullkarma** [comment]
Thanks okkez. I was wondering if I can pair it with concat. I'll give it a try and close this issue.

**Comment by nullkarma** [comment]
Works. Thanks for the hint and sample config.
closed.
