### ISSUE TITLE
Negate Multiline Regex

### ISSUE THREAD

**Issue by bcharboneauiherb** [fluent/fluent-plugin-grok-parser#38]
Is it possible to negate the multiline regex?
it works on http://grokconstructor.appspot.com and in logstash/filebeat just trying to make work in fluentd to replace logstash and filebeat.

Using the following grok and multiline regex:
grok pattern:  
\[%{TIMESTAMP_ISO8601:sourceTimestamp}\]\s\|\s(?<appName>.*?)\s\|\s\[(?<thread>.*?)\]\s\|\s\[%{IPORHOST:tempHost}\]\s\|\s%{LOGLEVEL:level}\s\|\s(?<userAgent>.*?)\s\|\s%{IPORHOST:ipAddress}\s\|\s(?<page>.*?)\s\|\s?(?<referrer>.*?)?\s?\|\s(?<tempMessage>(.|\r|\n)*)

multiline regex: ^[0-9]+

Data:
```
[2018-01-10 13:22:01,128] | ServiceName | [84] | [ServerName] | ERROR | Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html) | 66.249.73.137 | /pro/visitedproduct?pid=50724 | http://www.example.com/pr/quinn-popcorn-microwave-popcorn-vermont-maple-sea-salt-2-bags-3-6-oz-102-g-each/50724 | System.Web.HttpException (0x80004005): A public action method 'visitedproduct' was not found on controller 'iHerb.Web.Catalog.Controllers.ProController'.
   at System.Web.Mvc.Controller.HandleUnknownAction(String actionName)
   at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

**Comment by okkez** [comment]
What do you mean "negate the multiline regex"?
Do you want to filter logs like `grep -v`?
Could you show me your expected result and input and following information?

* fluentd version
* full configuration to reproduce your situation
* given input (data, log)
* expected result

**Comment by bcharboneauiherb** [comment]
fluentd version 1.0
Full configuration:
<source>
  @type tail
  path C:/logs/catalog_exceptions/*.txt
  tag catalog
  <parse>
    @type multiline_grok
    grok_pattern \[%{TIMESTAMP_ISO8601:sourceTimestamp}\]\s\|\s(?<appName>.*?)\s\|\s\[(?<thread>.*?)\]\s\|\s\[%{IPORHOST:tempHost}\]\s\|\s%{LOGLEVEL:level}\s\|\s(?<userAgent>.*?)\s\|\s%{IPORHOST:ipAddress}\s\|\s(?<page>.*?)\s\|\s?(?<referrer>.*?)?\s?\|\s(?<tempMessage>(.|\r|\n)*)
  </parse>
</source>

Input data in previous post under data block

Expected result:

[2018-01-10 13:22:01,128] | ServiceName | [84] | [ServerName] | ERROR | Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html) | 66.249.73.137 | /pro/visitedproduct?pid=50724 | http://www.example.com/pr/quinn-popcorn-microwave-popcorn-vermont-maple-sea-salt-2-bags-3-6-oz-102-g-each/50724 | System.Web.HttpException (0x80004005): A public action method 'visitedproduct' was not found on controller 'iHerb.Web.Catalog.Controllers.ProController'. at System.Web.Mvc.Controller.HandleUnknownAction(String actionName) at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

Formatted result

tempMessage	System.Web.HttpException·(0x80004005):·A·public·action·method·'visitedproduct'·was·not·found·on·controller·'iHerb.Web.Catalog.Controllers.ProController'. ···at·System.Web.Mvc.Controller.HandleUnknownAction(String·actionName) ···at·System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult·asyncResult,·ExecuteCoreState·innerState) ···at·System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult·asyncResult) ···at·System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult·asyncResult) ···at·System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult·asyncResult) ···at·System.Web.Mvc.Controller.EndExecute(IAsyncResult·asyncResult) ···at·System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult·asyncResult,·ProcessRequestState·innerState) ···at·System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult·asyncResult) ···at·System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult·asyncResult) ···at·System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() ···at·System.Web.HttpApplication.ExecuteStep(IExecutionStep·step,·Boolean&·completedSynchronously)
appName	ServiceName
tempHost	ServerName
page	/pro/visitedproduct?pid=50724
userAgent	Mozilla/5.0·(compatible;·Googlebot/2.1;·+http://www.google.com/bot.html)
thread	84
sourceTimestamp	2018-01-10·13:22:01,128
ipAddress	66.249.73.137
referrer	http://www.example.com/pr/quinn-popcorn-microwave-popcorn-vermont-maple-sea-salt-2-bags-3-6-oz-102-g-each/50724
level	ERROR

**Comment by okkez** [comment]
Did you mean that you want to concatenate stacktrace lines in one event log?
If so, you can use [fluent-plugin-concat](https://github.com/fluent-plugins-nursery/fluent-plugin-concat).

```
<source>
  @type tail
  path C:/logs/catalog_exceptions/*.txt
  tag catalog path
  <parse>
    @type none
  </parse>
  @label @INPUT
</source>
<label @INPUT>
  <filter>
    @type concat
    key message
    multiline_start_regexp /^[/
    continuous_line_regexp /^\s+/
  </filter>
  <filter>
    @type parser
    # you can parse concatenated logs here
    <parse>
      @type multiline_grok
     <grok>
        # your grok pattern here
     </grok>
    </parse>
  </filter>
  <match **>
    @type stdout
  </match>
</label>
```

**Comment by bcharboneauiherb** [comment]
I will give that a shot and see if it produces the desired result. If not, maybe we can find another way. If it works i will close the issue.

**Comment by bcharboneauiherb** [comment]
Please see the attached image here is the error i get now. Config and Error in same screenshot.
Note: "grok_pattern" and actual pattern are on same line just wordwrapping caused it to move.
regexp for concat did not appear to work as provided errored out in concat plugin. you will see that i changed them slightly to get to get to the point where grok plugin is reading the text.
![image](https://user-images.githubusercontent.com/25490249/34841171-2c9dac06-f6bc-11e7-84c3-77851dc2d6e6.png)

**Comment by okkez** [comment]
`key_name` parameter is required for filter_parser plugin.
You must add `key_name` parameter like following:

```
<source>
  @type tail
  path C:/logs/catalog_exceptions/*.txt
  tag catalog path
  <parse>
    @type none
  </parse>
  @label @INPUT
</source>
<label @INPUT>
  <filter>
    @type concat
    key message
    multiline_start_regexp /^[/
    continuous_line_regexp /^\s+/
  </filter>
  <filter>
    @type parser
    key_name message  # Add this line
    # you can parse concatenated logs here
    <parse>
      @type multiline_grok
     <grok>
        # your grok pattern here
        pattern %{YOUR_GROK_PATTERN_HERE} # not grok_pattern
     </grok>
    </parse>
  </filter>
  <match **>
    @type stdout
  </match>
</label>
```

**Comment by bcharboneauiherb** [comment]
while it works with the concat. is there any way to use you multiline_grok feature without concat in my case?

I do not necessarily need it to be concatenated, i do need all lines that follow to be included in a sigle record until the next sourceTimestamp.

Note the "continuous_line_regexp" does not appear to be doing anything that is why it is removed.

here is what i have that sort of works with concat.

<source>
  @type tail
  path C:/logs/catalog_exceptions/*.txt
  tag catalog
  <parse>
    @type none
  </parse>
  @label @INPUT
</source>

<label @INPUT>
  <filter>
    @type concat
    key message
    multiline_start_regexp /\[[0-9][0-9][0-9][0-9]/
  </filter>
  <filter>
    @type parser
	key_name message
    # you can parse concatenated logs here

    <parse>
      @type grok
      <grok>
	    pattern \[%{TIMESTAMP_ISO8601:sourceTimestamp}]\s\|\s(?<appName>.*?)\s\|\s\[(?<thread>.*?)\]\s\|\s\[%{IPORHOST:tempHost}\]\s\|\s%{LOGLEVEL:level}\s\|\s(?<userAgent>.*?)\s\|\s%{IPORHOST:ipAddress}\s\|\s(?<page>.*?)\s\|\s?(?<referrer>.*?)?\s?\|\s(?<tempMessage>(.|\r|\n)*)
	  </grok>
    </parse>
  </filter>
  <match **>
    @type stdout
  </match>
</label>

**Comment by okkez** [comment]
You can use In_tail's `<parse>` section like following:

```
<source>
  @type tail
  path 40.log
  pos_file 40.log.pos
  tag dummy.log
  read_from_head true
  <parse>
    @type multiline_grok
    multiline_start_regexp /^[A-Z]+ \[\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}\].*/
    <grok>
      pattern %{LOGLEVEL:loglevel}\s*\[(?<sourceTimestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3})\]\s%{GREEDYDATA:m}
    </grok>
  </parse>
  @label @INPUT
</source>

<label @INPUT>
  <match dummy.log>
    @type stdout
  </match>
</label>
```

But this does not work well.

* `in_tail` and `multiline_grok`
  * :+1: less dependency
  * :-1: users must understand `in_tail` internal behavior
  * :-1: it is hard to handle unfinished logs properly (`multiline_flush_interval` may help this)
* `in_tail`, `filter_concat` and `multiline_grok`
  * :100: works perfectly!

**Comment by bcharboneauiherb** [comment]
Works like a charm. If i run into issues with in_tail I may go back to the concat way you described. But for now it is working without the concat.
Thank you for all the help.
